# Generated by Django 3.1.5 on 2021-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCryo',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField()),
            ],
        ),
    ]
