# Generated by Django 3.1.5 on 2021-01-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_aboutcryo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCryo',
        ),
    ]
