# Generated by Django 3.1.5 on 2021-01-27 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_delete_aboutcryo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 12, 45, 8, 965546)),
        ),
    ]
